/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ItemsOrdered {
  'productName' : string,
  'quantity' : bigint,
  'price' : number,
}
export interface Order {
  'contact' : string,
  'name' : string,
  'totalAmount' : number,
  'address' : string,
  'timestamp' : bigint,
  'items' : Array<ItemsOrdered>,
}
export interface _SERVICE {
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getVisitorCount' : ActorMethod<[], bigint>,
  'incrementVisitorCount' : ActorMethod<[], undefined>,
  'placeOrder' : ActorMethod<
    [string, string, string, Array<ItemsOrdered>, number],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];