/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ItemsOrdered = IDL.Record({
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const Order = IDL.Record({
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'address' : IDL.Text,
  'timestamp' : IDL.Int,
  'items' : IDL.Vec(ItemsOrdered),
});

export const idlService = IDL.Service({
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrder' : IDL.Func([IDL.Int], [Order], ['query']),
  'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
  'incrementVisitorCount' : IDL.Func([], [], []),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ItemsOrdered), IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ItemsOrdered = IDL.Record({
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const Order = IDL.Record({
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'address' : IDL.Text,
    'timestamp' : IDL.Int,
    'items' : IDL.Vec(ItemsOrdered),
  });
  
  return IDL.Service({
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrder' : IDL.Func([IDL.Int], [Order], ['query']),
    'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
    'incrementVisitorCount' : IDL.Func([], [], []),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ItemsOrdered), IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };